### ISSUE TITLE
feat:Real-Time Face Tracking

### ISSUE THREAD

**Issue by sinanverve7** [capawesome-team/capacitor-mlkit#167]
### Plugin(s)

- [ ] Barcode Scanning
- [X] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

I am currently using the @capacitor-mlkit/face-detection plugin to verify users' selfies. However, many users upload images of chairs, walls, or other irrelevant objects instead of their faces. Additionally, some users rotate their heads and upload images showing only their right or left ear. This leads to unsuccessful selfie verifications. To address this, I need a way to provide real-time feedback to users, prompting them to make their face fully visible in the camera preview.

### Preferred solution

please Integrate real-time face tracking using Apple's Vision framework into the @capacitor-mlkit/face-detection library, as detailed in [Apple's documentation on tracking the user's face in real time](https://developer.apple.com/documentation/vision/original_objective-c_and_swift_api/tracking_the_user_s_face_in_real_time).

### Additional context
Did omit this feature because of increased app size  ?

_No response_

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
The Capacitor MLKit plugins are intended to make the MLKit SDKs accessible for Capacitor apps. The integration of Apple's Vision framework is therefore out of scope.
